import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
// <Link> tag allows navigation with full page refresh, unlike <a> tag
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <header>
          <nav>
            <img />
            <Link href="/"> Home</Link>
            <Link href="/events"> Events</Link>
            <Link href="/about-us"> About Us</Link>
          </nav>
        </header>
        <main className={styles.main}></main>
        <footer className={styles.footer}>
          <p>&copy; {new Date().getFullYear()} Events App</p>
          <p>Powered by Next.js</p>
        </footer>
      </div>
    </>
  );
}
